<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PoliceStationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::insert('INSERT INTO `police_stations` (`id`, `district_id`, `en_name`, `bn_name`, `slug`, `lat`, `long`, `url`, `status_active`, `is_delete`, `created_by`, `updated_by`, `created_at`, `updated_at`) 
            VALUES (1, 1, "Palton", "Palton", "palton", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (2, 1, "Sutrapur", "Sutrapur", "sutrapur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (3, 1, "Chalk Bazar", "Chalk Bazar", "chalk-bazar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (4, 1, "Hazaribag", "Hazaribag", "hazaribag", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (5, 1, "Lalbag", "Lalbag", "lalbag", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (6, 1, "Kutuali", "Kutuali", "kutuali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (7, 1, "Gendaria", "Gendaria", "gendaria", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (8, 1, "Jatrabari", "Jatrabari", "jatrabari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (9, 1, "Wari", "Wari", "wari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (10, 1, "Bongshal", "Bongshal", "bongshal", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (11, 1, "Sampur", "Sampur", "sampur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (12, 1, "Kadamtoli", "Kadamtoli", "kadamtoli", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (13, 1, "Motijheel", "Motijheel", "motijheel", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (14, 1, "Newmarket", "Newmarket", "newmarket", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (15, 1, "Hatir Jheel", "Hatir Jheel", "hatir-jheel", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (16, 1, "Banani", "Banani", "banani", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (17, 1, "Shahbag", "Shahbag", "shahbag", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (18, 1, "Cantonment", "Cantonment", "cantonment", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (19, 1, "Ramna", "Ramna", "ramna", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (20, 1, "Muhammadpur", "Muhammadpur", "muhammadpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (21, 1, "Tejgaon", "Tejgaon", "tejgaon", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (22, 1, "Kasrul", "Kasrul", "kasrul", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (23, 1, "Sher-E-Banglanagar", "Sher-E-Banglanagar", "sher-e-banglanagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (24, 1, "Shahali", "Shahali", "shahali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (25, 1, "Mirpur", "Mirpur", "mirpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (26, 1, "Badda", "Badda", "badda", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (27, 1, "Hazaribagh", "Hazaribagh", "hazaribagh", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (28, 1, "Uttara West", "Uttara West", "uttara-west", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (29, 1, "Tejgaon Industrial area", "Tejgaon Industrial area", "tejgaon-industrial-area", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (30, 1, "Pallabi", "Pallabi", "pallabi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (31, 1, "Gulshan", "Gulshan", "gulshan", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (32, 1, "Sobujbag", "Sobujbag", "sobujbag", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (33, 1, "Khilgaon", "Khilgaon", "khilgaon", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (34, 1, "Khilkhet", "Khilkhet", "khilkhet", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (35, 1, "Vatara", "Vatara", "vatara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (36, 1, "Uttarkhan", "Uttarkhan", "uttarkhan", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (37, 1, "Rampura", "Rampura", "rampura", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (38, 1, "Mugda", "Mugda", "mugda", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (39, 1, "Dakshin Khan", "Dakshin Khan", "dakshin-khan", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (40, 1, "Turag", "Turag", "turag", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (41, 1, "Dohar", "Dohar", "dohar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (42, 1, "Savar", "Savar", "savar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (43, 1, "Dhamrai", "Dhamrai", "dhamrai", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (44, 1, "Keraniganj", "Keraniganj", "keraniganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (45, 1, "Nawabganj", "Nawabganj", "nawabganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (46, 1, "Demra", "Demra", "demra", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (47, 1, "Kodomtoli", "Kodomtoli", "kodomtoli", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (48, 2, "Faridpur Sadar", "Faridpur Sadar", "faridpur-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (49, 2, "Saltha", "Saltha", "saltha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (50, 2, "Charbadrashan", "Charbadrashan", "charbadrashan", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (51, 2, "Sadarpur", "Sadarpur", "sadarpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (52, 2, "Bhanga", "Bhanga", "bhanga", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (53, 2, "Nagarkanda", "Nagarkanda", "nagarkanda", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (54, 2, "Madukhali", "Madukhali", "madukhali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (55, 2, "Boalmari", "Boalmari", "boalmari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (56, 2, "Alfadanganga", "Alfadanganga", "alfadanganga", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (57, 3, "Gazipur sadar", "Gazipur sadar", "gazipur-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (58, 3, "Kaliganj", "Kaliganj", "kaliganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (59, 3, "Kapasia", "Kapasia", "kapasia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (60, 3, "Sreepur", "Sreepur", "sreepur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (61, 3, "Kaliakair", "Kaliakair", "kaliakair", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (62, 4, "Gopalganj Sadar", "Gopalganj Sadar", "gopalganj-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (63, 4, "Kotalipara", "Kotalipara", "kotalipara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (64, 4, "Tungipara", "Tungipara", "tungipara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (65, 4, "Kashiani", "Kashiani", "kashiani", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (66, 4, "Maksudpur", "Maksudpur", "maksudpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (67, 5, "Kishoreganj sadar", "Kishoreganj sadar", "kishoreganj-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (68, 5, "Karimganj", "Karimganj", "karimganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (69, 5, "Tarial", "Tarial", "tarial", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (70, 5, "Hossenpur", "Hossenpur", "hossenpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (71, 5, "Pakundia", "Pakundia", "pakundia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (72, 5, "Katiadi", "Katiadi", "katiadi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (73, 5, "Bajitpur", "Bajitpur", "bajitpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (74, 5, "Kuliarchar", "Kuliarchar", "kuliarchar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (75, 5, "Bhairab", "Bhairab", "bhairab", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (76, 5, "Nikli", "Nikli", "nikli", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (77, 5, "Mithamoin", "Mithamoin", "mithamoin", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (78, 5, "Ostagram", "Ostagram", "ostagram", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (79, 5, "Itna", "Itna", "itna", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (80, 6, "Madaripur Sadar", "Madaripur Sadar", "madaripur-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (81, 6, "Rajoir", "Rajoir", "rajoir", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (82, 6, "Kalkini", "Kalkini", "kalkini", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (83, 6, "Shibchar", "Shibchar", "shibchar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (84, 7, "Manikganj Sadar", "Manikganj Sadar", "manikganj-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (85, 7, "Saturia", "Saturia", "saturia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (86, 7, "Singair", "Singair", "singair", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (87, 7, "Hariampur", "Hariampur", "hariampur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (88, 7, "Gheor", "Gheor", "gheor", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (89, 7, "Shibaloy", "Shibaloy", "shibaloy", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (90, 7, "Doulatpur", "Doulatpur", "doulatpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (91, 8, "Munshiganj sadar", "Munshiganj sadar", "munshiganj-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (92, 8, "Gajaria", "Gajaria", "gajaria", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (93, 8, "Tangibari", "Tangibari", "tangibari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (94, 8, "Lohajong", "Lohajong", "lohajong", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (95, 8, "Sirajdikhan", "Sirajdikhan", "sirajdikhan", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (96, 8, "Srinagar", "Srinagar", "srinagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (97, 9, "Narayanganj Sadar", "Narayanganj Sadar", "narayanganj-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (98, 9, "Bandar", "Bandar", "bandar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (99, 9, "Araihazar", "Araihazar", "araihazar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (100, 9, "Rupganj", "Rupganj", "rupganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (101, 9, "Sonargaon", "Sonargaon", "sonargaon", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (102, 10, "Narshingdi Sadar", "Narshingdi Sadar", "narshingdi-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (103, 10, "Shibpur", "Shibpur", "shibpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (104, 10, "Belabo", "Belabo", "belabo", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (105, 10, "Monohordi", "Monohordi", "monohordi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (106, 10, "Palash", "Palash", "palash", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (107, 10, "Raypura", "Raypura", "raypura", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (108, 11, "Rajbari Sadar", "Rajbari Sadar", "rajbari-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (109, 11, "Goalanda", "Goalanda", "goalanda", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (110, 11, "Pangsha", "Pangsha", "pangsha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (111, 11, "Kalukhali", "Kalukhali", "kalukhali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (112, 11, "Baliakandi", "Baliakandi", "baliakandi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (113, 12, "Shariatpur Sadar", "Shariatpur Sadar", "shariatpur-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (114, 12, "Jajira", "Jajira", "jajira", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (115, 12, "Naria", "Naria", "naria", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (116, 12, "Badarganj", "Badarganj", "badarganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (117, 12, "Damudya", "Damudya", "damudya", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (118, 12, "Gosairhat", "Gosairhat", "gosairhat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (119, 13, "Tangail sadar", "Tangail sadar", "tangail-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (120, 13, "Delduar", "Delduar", "delduar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (121, 13, "Basail", "Basail", "basail", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (122, 13, "Nagarpur", "Nagarpur", "nagarpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (123, 13, "Mirzapur", "Mirzapur", "mirzapur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (124, 13, "Sakhipur", "Sakhipur", "sakhipur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (125, 13, "Bhuapur", "Bhuapur", "bhuapur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (126, 13, "Kalihati", "Kalihati", "kalihati", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (127, 13, "Ghatail", "Ghatail", "ghatail", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (128, 13, "Gopalpur", "Gopalpur", "gopalpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (129, 13, "Madhupur", "Madhupur", "madhupur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (130, 13, "Dhonbari", "Dhonbari", "dhonbari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (131, 14, "Bandorban Sadar", "Bandorban Sadar", "bandorban-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (132, 14, "Ruma", "Ruma", "ruma", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (133, 14, "Thanchi", "Thanchi", "thanchi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (134, 14, "Lama", "Lama", "lama", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (135, 14, "Rowangchari", "Rowangchari", "rowangchari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (136, 14, "Alikadam", "Alikadam", "alikadam", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (137, 14, "Naikhyongcharl", "Naikhyongcharl", "naikhyongcharl", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (138, 15, "Brahmanbaria Sadar", "Brahmanbaria Sadar", "brahmanbaria-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (139, 15, "Ashuganj", "Ashuganj", "ashuganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (140, 15, "Nabinagar", "Nabinagar", "nabinagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (141, 15, "Banchharampur Upzia", "Banchharampur Upzia", "banchharampur-upzia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (142, 15, "Sarail Upzila", "Sarail Upzila", "sarail-upzila", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (143, 15, "Nasirnagar", "Nasirnagar", "nasirnagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (144, 15, "Akhaura", "Akhaura", "akhaura", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (145, 15, "Kasba", "Kasba", "kasba", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (146, 15, "Bijoynagar", "Bijoynagar", "bijoynagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (147, 16, "Chandpur Sadar", "Chandpur Sadar", "chandpur-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (148, 16, "Shahrasti", "Shahrasti", "shahrasti", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (149, 16, "Motlob dokkhin", "Motlob dokkhin", "motlob-dokkhin", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (150, 16, "Motlob uttor", "Motlob uttor", "motlob-uttor", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (151, 16, "Faridgonj", "Faridgonj", "faridgonj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (152, 16, "Kachua", "Kachua", "kachua", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (153, 16, "Haimchar", "Haimchar", "haimchar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (154, 16, "Hazigonj", "Hazigonj", "hazigonj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (155, 17, "Kotwali", "Kotwali", "kotwali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (156, 17, "Double Mooring", "Double Mooring", "double-mooring", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (157, 17, "Akbarshah", "Akbarshah", "akbarshah", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (158, 17, "Patenga", "Patenga", "patenga", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (159, 17, "Pahartoli", "Pahartoli", "pahartoli", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (160, 17, "Bayazid", "Bayazid", "bayazid", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (161, 17, "Chandgaon", "Chandgaon", "chandgaon", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (162, 17, "Halishahar", "Halishahar", "halishahar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (163, 17, "Bandar", "Bandar", "bandar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (164, 17, "EPZ", "EPZ", "epz", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (165, 17, "Chawkbazar", "Chawkbazar", "chawkbazar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (166, 17, "Panchlaaish", "Panchlaaish", "panchlaaish", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (167, 17, "Khulsi", "Khulsi", "khulsi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (168, 17, "Karnaphuli", "Karnaphuli", "karnaphuli", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (169, 17, "Chandanish", "Chandanish", "chandanish", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (170, 17, "Patia", "Patia", "patia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (171, 17, "Anowara", "Anowara", "anowara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (172, 17, "Boalkhali", "Boalkhali", "boalkhali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (173, 17, "Rouzan", "Rouzan", "rouzan", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (174, 17, "Hathazari Upizala", "Hathazari Upizala", "hathazari-upizala", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (175, 17, "Mirsharai", "Mirsharai", "mirsharai", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (176, 17, "Sitakunda", "Sitakunda", "sitakunda", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (177, 17, "Sandwip", "Sandwip", "sandwip", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (178, 17, "Lohagara", "Lohagara", "lohagara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (179, 17, "Satkania", "Satkania", "satkania", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (180, 17, "Bashkhali", "Bashkhali", "bashkhali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (181, 17, "Fatikchhari", "Fatikchhari", "fatikchhari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (182, 17, "Rangunia", "Rangunia", "rangunia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (183, 18, "Cumilla Sadar South", "Cumilla Sadar South", "cumilla-sadar-south", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (184, 18, "Barura", "Barura", "barura", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (185, 18, "Laksam", "Laksam", "laksam", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (186, 18, "Nangolkot", "Nangolkot", "nangolkot", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (187, 18, "Lalmai", "Lalmai", "lalmai", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (188, 18, "Chouddagram", "Chouddagram", "chouddagram", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (189, 18, "Homna", "Homna", "homna", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (190, 18, "Meghna", "Meghna", "meghna", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (191, 18, "Titash", "Titash", "titash", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (192, 18, "Daudkandi", "Daudkandi", "daudkandi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (193, 18, "Burichong", "Burichong", "burichong", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (194, 18, "Brahmanpara", "Brahmanpara", "brahmanpara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (195, 18, "Muradnagar", "Muradnagar", "muradnagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (196, 18, "Debidwar UPO", "Debidwar UPO", "debidwar-upo", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (197, 18, "Monohorgonj", "Monohorgonj", "monohorgonj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (198, 18, "Chandina", "Chandina", "chandina", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (208, 20, "Feni Sadar", "Feni Sadar", "feni-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (209, 20, "Chagalnaia", "Chagalnaia", "chagalnaia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (210, 20, "Dagonbhuia", "Dagonbhuia", "dagonbhuia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (211, 20, "Sonagazi", "Sonagazi", "sonagazi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (212, 20, "Parshuram", "Parshuram", "parshuram", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (213, 20, "Fulgazi", "Fulgazi", "fulgazi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (214, 21, "Khagrachari Sadar", "Khagrachari Sadar", "khagrachari-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (215, 21, "Panchari", "Panchari", "panchari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (216, 21, "Dighinala", "Dighinala", "dighinala", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (217, 21, "Mahalchhari", "Mahalchhari", "mahalchhari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (218, 21, "Ramgor", "Ramgor", "ramgor", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (219, 21, "Guimara", "Guimara", "guimara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (220, 21, "Matiranga", "Matiranga", "matiranga", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (221, 21, "Manikchari", "Manikchari", "manikchari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (222, 21, "Laxmichari", "Laxmichari", "laxmichari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (223, 22, "Lakshmipur Sadar", "Lakshmipur Sadar", "lakshmipur-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (224, 22, "Raipur", "Raipur", "raipur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (225, 22, "Ramganj", "Ramganj", "ramganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (226, 22, "Ramgati", "Ramgati", "ramgati", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (227, 22, "Kamal nagar", "Kamal nagar", "kamal-nagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (228, 23, "Noakhali Sadar", "Noakhali Sadar", "noakhali-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (229, 23, "Suborno Char", "Suborno Char", "suborno-char", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (230, 23, "Hatiya", "Hatiya", "hatiya", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (231, 23, "Senbag", "Senbag", "senbag", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (232, 23, "Begumganj", "Begumganj", "begumganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (233, 23, "Sonaimuri", "Sonaimuri", "sonaimuri", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (234, 23, "Kabirhat", "Kabirhat", "kabirhat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (235, 23, "Chatkhil", "Chatkhil", "chatkhil", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (236, 23, "Kompaniganj", "Kompaniganj", "kompaniganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (237, 24, "Rangamati Sadar", "Rangamati Sadar", "rangamati-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (238, 24, "Rajsthali", "Rajsthali", "rajsthali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (239, 24, "Bilaichhori", "Bilaichhori", "bilaichhori", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (240, 24, "Kawkhali", "Kawkhali", "kawkhali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (241, 24, "Jurachori", "Jurachori", "jurachori", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (242, 24, "Barkal", "Barkal", "barkal", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (243, 24, "Langadu", "Langadu", "langadu", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (244, 24, "Baghaichari", "Baghaichari", "baghaichari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (245, 24, "Kaptai", "Kaptai", "kaptai", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (246, 24, "Naniarchar", "Naniarchar", "naniarchar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (247, 25, "Bagerhat Sadar", "Bagerhat Sadar", "bagerhat-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (248, 25, "Chitalmari", "Chitalmari", "chitalmari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (249, 25, "Fakirhat", "Fakirhat", "fakirhat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (250, 25, "Mollahat", "Mollahat", "mollahat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (251, 25, "Kachua", "Kachua", "kachua", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (252, 25, "Rampal", "Rampal", "rampal", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (253, 25, "Sharankhola", "Sharankhola", "sharankhola", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (254, 25, "Mongla", "Mongla", "mongla", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (255, 25, "Morrelganj", "Morrelganj", "morrelganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (256, 26, "Chuadanga Sadar", "Chuadanga Sadar", "chuadanga-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (257, 26, "Alamdanga", "Alamdanga", "alamdanga", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (258, 26, "Damurhuda", "Damurhuda", "damurhuda", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (259, 26, "Jibannagar", "Jibannagar", "jibannagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (260, 27, "Jashore Sadar", "Jashore Sadar", "jashore-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (261, 27, "Chougachha", "Chougachha", "chougachha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (262, 27, "Jhikargachha", "Jhikargachha", "jhikargachha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (263, 27, "Sarsa", "Sarsa", "sarsa", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (264, 27, "Monirampur", "Monirampur", "monirampur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (265, 27, "Keshobpur", "Keshobpur", "keshobpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (266, 27, "Bagharpara", "Bagharpara", "bagharpara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (267, 27, "Abhaynagar Noapara", "Abhaynagar Noapara", "abhaynagar-noapara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (268, 28, "Jhenaidah Sadar", "Jhenaidah Sadar", "jhenaidah-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (269, 28, "Horinakundu", "Horinakundu", "horinakundu", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (270, 28, "Shailakupa", "Shailakupa", "shailakupa", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (271, 28, "Kotchandpur", "Kotchandpur", "kotchandpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (272, 28, "Maheshpur", "Maheshpur", "maheshpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (273, 28, "Kaliganj", "Kaliganj", "kaliganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (274, 29, "Khulna Kotwali", "Khulna Kotwali", "khulna-kotwali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (275, 29, "Khalishpur", "Khalishpur", "khalishpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (276, 29, "Sonadanga", "Sonadanga", "sonadanga", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (277, 29, "Doulatpur", "Doulatpur", "doulatpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (278, 29, "Khanjahan Ail", "Khanjahan Ail", "khanjahan-ail", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (279, 29, "Labanchora", "Labanchora", "labanchora", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (280, 29, "Horintana", "Horintana", "horintana", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (281, 29, "Koyra", "Koyra", "koyra", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (282, 29, "Dumuria", "Dumuria", "dumuria", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (283, 29, "Tarokhada", "Tarokhada", "tarokhada", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (284, 29, "Dacope", "Dacope", "dacope", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (285, 29, "Digalia", "Digalia", "digalia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (286, 29, "Paikgachha", "Paikgachha", "paikgachha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (287, 29, "Batiaghata", "Batiaghata", "batiaghata", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (288, 29, "Phultala", "Phultala", "phultala", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (289, 29, "Rupsa", "Rupsa", "rupsa", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (290, 30, "Kushtia Sadar", "Kushtia Sadar", "kushtia-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (291, 30, "Kumarkhali", "Kumarkhali", "kumarkhali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (292, 30, "Khoksa", "Khoksa", "khoksa", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (293, 30, "Mirpur", "Mirpur", "mirpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (294, 30, "Bheramara", "Bheramara", "bheramara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (295, 30, "Daulatpur", "Daulatpur", "daulatpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (296, 31, "Magura Sadar", "Magura Sadar", "magura-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (297, 31, "Sreepur", "Sreepur", "sreepur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (298, 31, "Shalikha", "Shalikha", "shalikha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (299, 31, "Mohammadpur", "Mohammadpur", "mohammadpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (300, 32, "Meherpur Sadar", "Meherpur Sadar", "meherpur-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (301, 32, "Mujibnagar", "Mujibnagar", "mujibnagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (302, 32, "Gangni", "Gangni", "gangni", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (303, 33, "Narail Sadar", "Narail Sadar", "narail-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (304, 33, "Lohagara", "Lohagara", "lohagara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (305, 33, "Kalia", "Kalia", "kalia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (306, 34, "Satkhira", "Satkhira", "satkhira", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (307, 34, "Tala", "Tala", "tala", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (308, 34, "Devhata", "Devhata", "devhata", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (309, 34, "Kalaroa", "Kalaroa", "kalaroa", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (310, 34, "Kaliganj", "Kaliganj", "kaliganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (311, 34, "Shyamnagar", "Shyamnagar", "shyamnagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (312, 34, "Ashashuni", "Ashashuni", "ashashuni", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (313, 35, "Bogura Sadar", "Bogura Sadar", "bogura-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (314, 35, "Adamdighi", "Adamdighi", "adamdighi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (315, 35, "Dhunat", "Dhunat", "dhunat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (316, 35, "Dupchachia", "Dupchachia", "dupchachia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (317, 35, "Gabtoli", "Gabtoli", "gabtoli", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (318, 35, "Kahalu", "Kahalu", "kahalu", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (319, 35, "Nandigram", "Nandigram", "nandigram", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (320, 35, "Sariakandi", "Sariakandi", "sariakandi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (321, 35, "Sherpur", "Sherpur", "sherpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (322, 35, "Shibgonj", "Shibgonj", "shibgonj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (323, 35, "Sonatola", "Sonatola", "sonatola", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (324, 35, "Sajahanpur", "Sajahanpur", "sajahanpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (325, 36, "Joypurhat Sadar", "Joypurhat Sadar", "joypurhat-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (326, 36, "Panchbibi", "Panchbibi", "panchbibi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (327, 36, "Kalai", "Kalai", "kalai", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (328, 36, "Khetlal", "Khetlal", "khetlal", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (329, 36, "Akkelpur", "Akkelpur", "akkelpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (330, 37, "Nogaon Sadar", "Nogaon Sadar", "nogaon-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (331, 37, "Patnitola", "Patnitola", "patnitola", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (332, 37, "Dhamurhat", "Dhamurhat", "dhamurhat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (333, 37, "Mohadebpur", "Mohadebpur", "mohadebpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (334, 37, "Porsha", "Porsha", "porsha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (335, 37, "Sapahar", "Sapahar", "sapahar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (336, 37, "Badalgachi", "Badalgachi", "badalgachi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (337, 37, "Manda", "Manda", "manda", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (338, 37, "Niamotpur", "Niamotpur", "niamotpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (339, 37, "Atrai", "Atrai", "atrai", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (340, 37, "Raninagar", "Raninagar", "raninagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (341, 38, "Natore Sadar", "Natore Sadar", "natore-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (342, 38, "Bagatipara", "Bagatipara", "bagatipara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (343, 38, "Boraigram", "Boraigram", "boraigram", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (344, 38, "Gurudaspur", "Gurudaspur", "gurudaspur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (345, 38, "Singra", "Singra", "singra", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (346, 38, "Noldanga", "Noldanga", "noldanga", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (347, 38, "Lalpur", "Lalpur", "lalpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (348, 39, "Chapai Sadar", "Chapai Sadar", "chapai-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (349, 39, "Gamostapur", "Gamostapur", "gamostapur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (350, 39, "Shibganj", "Shibganj", "shibganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (351, 39, "Nachol", "Nachol", "nachol", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (352, 39, "Bholahat", "Bholahat", "bholahat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (353, 40, "Pabna Sadar", "Pabna Sadar", "pabna-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (354, 40, "Atgharia", "Atgharia", "atgharia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (355, 40, "Ishwardi", "Ishwardi", "ishwardi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (356, 40, "Chatmohar", "Chatmohar", "chatmohar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (357, 40, "Faridpud", "Faridpud", "faridpud", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (358, 40, "Bera", "Bera", "bera", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (359, 40, "Bhangura", "Bhangura", "bhangura", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (360, 40, "Santhia", "Santhia", "santhia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (361, 40, "Sujanagar", "Sujanagar", "sujanagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (362, 41, "Bagha", "Bagha", "bagha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (363, 41, "Puthia", "Puthia", "puthia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (364, 41, "Poba", "Poba", "poba", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (365, 41, "Baghmara", "Baghmara", "baghmara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (366, 41, "Durgapur", "Durgapur", "durgapur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (367, 41, "Tanore", "Tanore", "tanore", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (368, 41, "Charghat", "Charghat", "charghat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (369, 41, "Godagari", "Godagari", "godagari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (370, 41, "Mohonpur", "Mohonpur", "mohonpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (371, 41, "katakhali", "katakhali", "katakhali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (372, 41, "Motihar", "Motihar", "motihar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (373, 41, "Rajpara", "Rajpara", "rajpara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (374, 41, "Kashiadanga", "Kashiadanga", "kashiadanga", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (375, 41, "Boalia", "Boalia", "boalia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (376, 41, "Shahmokdum", "Shahmokdum", "shahmokdum", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (377, 41, "Chandrima", "Chandrima", "chandrima", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (378, 42, "Sirajganj Sadar", "Sirajganj Sadar", "sirajganj-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (379, 42, "Ullapar", "Ullapar", "ullapar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (380, 42, "Kazipur", "Kazipur", "kazipur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (381, 42, "Kamar Khanda", "Kamar Khanda", "kamar-khanda", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (382, 42, "Chouhali", "Chouhali", "chouhali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (383, 42, "Tarash", "Tarash", "tarash", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (384, 42, "Belkuchi", "Belkuchi", "belkuchi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (385, 42, "Rayganj", "Rayganj", "rayganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (386, 42, "Shahjadpur", "Shahjadpur", "shahjadpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (387, 43, "Hobiganj Sadar", "Hobiganj Sadar", "hobiganj-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (388, 43, "Shaestaganj", "Shaestaganj", "shaestaganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (389, 43, "Madhabpur", "Madhabpur", "madhabpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (390, 43, "Lakhai", "Lakhai", "lakhai", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (391, 43, "Azmireeganj", "Azmireeganj", "azmireeganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (392, 43, "Baniachang", "Baniachang", "baniachang", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (393, 43, "Bahubal", "Bahubal", "bahubal", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (394, 43, "Chunarughat", "Chunarughat", "chunarughat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (395, 43, "Nabiganj", "Nabiganj", "nabiganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (396, 44, "Moulvibazar Sadar", "Moulvibazar Sadar", "moulvibazar-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (397, 44, "Baralekha", "Baralekha", "baralekha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (398, 44, "Kulaura", "Kulaura", "kulaura", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (399, 44, "Juri", "Juri", "juri", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (400, 44, "Srimangal", "Srimangal", "srimangal", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (401, 44, "Kamalganj", "Kamalganj", "kamalganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (402, 44, "Rajnagar", "Rajnagar", "rajnagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (403, 45, "Sunamganj Sadar", "Sunamganj Sadar", "sunamganj-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (404, 45, "Chatak", "Chatak", "chatak", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (405, 45, "Jagannathpur", "Jagannathpur", "jagannathpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (406, 45, "Tahirpur", "Tahirpur", "tahirpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (407, 45, "Jamalganj", "Jamalganj", "jamalganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (408, 45, "Shalla", "Shalla", "shalla", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (409, 45, "Derai", "Derai", "derai", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (410, 45, "Duarabazar", "Duarabazar", "duarabazar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (411, 45, "Biswombhorpur", "Biswombhorpur", "biswombhorpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (412, 45, "Santigonj", "Santigonj", "santigonj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (413, 45, "Moddonagar", "Moddonagar", "moddonagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (414, 45, "Dormopasha", "Dormopasha", "dormopasha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (415, 46, "Sylhet sadar", "Sylhet sadar", "sylhet-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (416, 46, "Dakshin Surma", "Dakshin Surma", "dakshin-surma", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (417, 46, "Fenchuganj", "Fenchuganj", "fenchuganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (418, 46, "Balaganj", "Balaganj", "balaganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (419, 46, "Osmani Nagar", "Osmani Nagar", "osmani-nagar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (420, 46, "Bishwanath", "Bishwanath", "bishwanath", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (421, 46, "Companiganj", "Companiganj", "companiganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (422, 46, "Goainghat", "Goainghat", "goainghat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (423, 46, "Jaintapur", "Jaintapur", "jaintapur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (424, 46, "Golapganj", "Golapganj", "golapganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (425, 46, "Beanibazar", "Beanibazar", "beanibazar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (426, 46, "Kanaighat", "Kanaighat", "kanaighat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (427, 46, "Zakigonj", "Zakigonj", "zakigonj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (428, 47, "Barguna Sadar", "Barguna Sadar", "barguna-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (429, 47, "Amtali", "Amtali", "amtali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (430, 47, "Taltali", "Taltali", "taltali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (431, 47, "Patharghata", "Patharghata", "patharghata", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (432, 47, "Bamna", "Bamna", "bamna", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (433, 47, "Betagi", "Betagi", "betagi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (434, 48, "Barishal Sadar", "Barishal Sadar", "barishal-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (435, 48, "Bakerganj", "Bakerganj", "bakerganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (436, 48, "Babuganj", "Babuganj", "babuganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (437, 48, "Uzirpur", "Uzirpur", "uzirpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (438, 48, "Gouranadi", "Gouranadi", "gouranadi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (439, 48, "Agailzhara", "Agailzhara", "agailzhara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (440, 48, "Muladi", "Muladi", "muladi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (441, 48, "Hizla", "Hizla", "hizla", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (442, 48, "Mahendiganj", "Mahendiganj", "mahendiganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (443, 48, "Banaripara", "Banaripara", "banaripara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (444, 49, "Bhola Sadar", "Bhola Sadar", "bhola-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (445, 49, "Doulatkhan", "Doulatkhan", "doulatkhan", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (446, 49, "Borhanuddin", "Borhanuddin", "borhanuddin", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (447, 49, "Lalmohan", "Lalmohan", "lalmohan", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (448, 49, "Charfashion", "Charfashion", "charfashion", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (449, 49, "Tojumoddin", "Tojumoddin", "tojumoddin", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (450, 49, "Monpura", "Monpura", "monpura", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (451, 50, "Jhalokathi Sadar", "Jhalokathi Sadar", "jhalokathi-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (452, 50, "Rajapur", "Rajapur", "rajapur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (453, 50, "Nalchhiti", "Nalchhiti", "nalchhiti", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (454, 50, "Kathalia", "Kathalia", "kathalia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (455, 51, "Patuakhali sadar", "Patuakhali sadar", "patuakhali-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (456, 51, "Dumki", "Dumki", "dumki", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (457, 51, "Mirzaganj", "Mirzaganj", "mirzaganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (458, 51, "Bauphal", "Bauphal", "bauphal", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (459, 51, "Dashmina", "Dashmina", "dashmina", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (460, 51, "Galachipa", "Galachipa", "galachipa", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (461, 51, "Rangabali", "Rangabali", "rangabali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (462, 51, "Kalapara", "Kalapara", "kalapara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (463, 52, "Pirojpur Sadar", "Pirojpur Sadar", "pirojpur-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (464, 52, "Indurkani", "Indurkani", "indurkani", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (465, 52, "Kaukhali", "Kaukhali", "kaukhali", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (467, 52, "Nasarabad (Swarupkathi)", "Nasarabad (Swarupkathi)", "nasarabad-swarupkathi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (468, 52, "Nazirpur", "Nazirpur", "nazirpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (469, 52, "Bhandaria", "Bhandaria", "bhandaria", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (470, 52, "Mathbaria", "Mathbaria", "mathbaria", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (471, 53, "Jamalpur Sadar", "Jamalpur Sadar", "jamalpur-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (472, 53, "Melandaha", "Melandaha", "melandaha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (473, 53, "Islampur", "Islampur", "islampur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (474, 53, "Dewanganj", "Dewanganj", "dewanganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (475, 53, "Madarganj", "Madarganj", "madarganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (476, 53, "Sarishabari", "Sarishabari", "sarishabari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (477, 53, "Bakshigonj", "Bakshigonj", "bakshigonj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (478, 54, "Mymensingh sadar", "Mymensingh sadar", "mymensingh-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (479, 54, "Muktagachha", "Muktagachha", "muktagachha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (480, 54, "Fulbaria", "Fulbaria", "fulbaria", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (481, 54, "Trishal", "Trishal", "trishal", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (482, 54, "Gaforgaon", "Gaforgaon", "gaforgaon", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (483, 54, "Bhaluka", "Bhaluka", "bhaluka", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (484, 54, "Phulpur", "Phulpur", "phulpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (485, 54, "Tarakanda", "Tarakanda", "tarakanda", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (486, 54, "Haluaghat", "Haluaghat", "haluaghat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (487, 54, "Gouripur", "Gouripur", "gouripur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (488, 54, "Isshwargonj", "Isshwargonj", "isshwargonj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (489, 54, "Dhobaura", "Dhobaura", "dhobaura", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (490, 54, "Nandail UPO", "Nandail UPO", "nandail-upo", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (491, 55, "Netrakona Sadar", "Netrakona Sadar", "netrakona-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (492, 55, "Purbadhola", "Purbadhola", "purbadhola", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (493, 55, "Susung Durgapur", "Susung Durgapur", "susung-durgapur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (494, 55, "Kalmakanda", "Kalmakanda", "kalmakanda", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (495, 55, "Barhatta", "Barhatta", "barhatta", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (496, 55, "Mohanganj", "Mohanganj", "mohanganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (497, 55, "Khaliajuri", "Khaliajuri", "khaliajuri", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (498, 55, "Atpara", "Atpara", "atpara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (499, 55, "Kendua", "Kendua", "kendua", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (500, 55, "Madan", "Madan", "madan", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (501, 56, "Sherpur Sadar", "Sherpur Sadar", "sherpur-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (502, 56, "Nalitabari", "Nalitabari", "nalitabari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (503, 56, "Jhinaigati", "Jhinaigati", "jhinaigati", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (504, 56, "Shribardi", "Shribardi", "shribardi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (505, 56, "Nakla", "Nakla", "nakla", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (506, 57, "Dinajpur", "Dinajpur", "dinajpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (507, 57, "Parbatipur", "Parbatipur", "parbatipur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (508, 57, "Birampur", "Birampur", "birampur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (509, 57, "Birganj", "Birganj", "birganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (510, 57, "Biral", "Biral", "biral", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (511, 57, "Bachaganj", "Bachaganj", "bachaganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (512, 57, "Chrirbandar", "Chrirbandar", "chrirbandar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (513, 57, "Phulbari", "Phulbari", "phulbari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (514, 57, "Ghoraghat", "Ghoraghat", "ghoraghat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (515, 57, "Hakimpur", "Hakimpur", "hakimpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (516, 57, "Kaharole", "Kaharole", "kaharole", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (517, 57, "Khansama", "Khansama", "khansama", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (518, 57, "Nababganj", "Nababganj", "nababganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (519, 58, "Gaibandha Sadar", "Gaibandha Sadar", "gaibandha-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (520, 58, "Phulchari", "Phulchari", "phulchari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (521, 58, "Gobindoganj", "Gobindoganj", "gobindoganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (522, 58, "Palashbsri", "Palashbsri", "palashbsri", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (523, 58, "Saghata", "Saghata", "saghata", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (524, 58, "Sundarganj", "Sundarganj", "sundarganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (525, 58, "Saadullapur", "Saadullapur", "saadullapur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (526, 59, "Kurigram ‍Sadar", "Kurigram ‍Sadar", "kurigram-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (527, 59, "Bhurungamari", "Bhurungamari", "bhurungamari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (528, 59, "Ulipur", "Ulipur", "ulipur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (529, 59, "Chilmari", "Chilmari", "chilmari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (530, 59, "Phulbari", "Phulbari", "phulbari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (531, 59, "Rajarhat", "Rajarhat", "rajarhat", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (532, 59, "Nageshwari", "Nageshwari", "nageshwari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (533, 59, "Roumari", "Roumari", "roumari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (534, 59, "Rajibpur", "Rajibpur", "rajibpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (535, 60, "Lalmonirhat Sadar", "Lalmonirhat Sadar", "lalmonirhat-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (536, 60, "Aditmari", "Aditmari", "aditmari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (537, 60, "Hatibandha", "Hatibandha", "hatibandha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (538, 60, "Kaliganj", "Kaliganj", "kaliganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (539, 60, "patgram", "patgram", "patgram", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (540, 61, "Nilphamari ‍Sadar", "Nilphamari ‍Sadar", "nilphamari-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (541, 61, "Dimla", "Dimla", "dimla", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (542, 61, "Domar", "Domar", "domar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (543, 61, "Jaldhaka", "Jaldhaka", "jaldhaka", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (544, 61, "Kishoriganj", "Kishoriganj", "kishoriganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (545, 61, "Syedpur", "Syedpur", "syedpur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (546, 62, "Panchagarh", "Panchagarh", "panchagarh", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (547, 62, "Boda", "Boda", "boda", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (548, 62, "Dabiganj", "Dabiganj", "dabiganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (549, 62, "Atwari", "Atwari", "atwari", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (550, 62, "Telulia", "Telulia", "telulia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (551, 63, "Rangpur Sadar", "Rangpur Sadar", "rangpur-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (552, 63, "Gangachara", "Gangachara", "gangachara", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (553, 63, "Badarganj", "Badarganj", "badarganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (554, 63, "Kaunia", "Kaunia", "kaunia", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (555, 63, "Mithapukur", "Mithapukur", "mithapukur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (556, 63, "Pirganj", "Pirganj", "pirganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (557, 63, "Pirgacha", "Pirgacha", "pirgacha", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (558, 63, "Taraganj", "Taraganj", "taraganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (559, 64, "Thakurgaon", "Thakurgaon", "thakurgaon", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (560, 64, "Baliadangi", "Baliadangi", "baliadangi", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (561, 64, "Horipur", "Horipur", "horipur", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (562, 64, "Pirganj", "Pirganj", "pirganj", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (563, 64, "Rani Sankail", "Rani Sankail", "rani-sankail", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (565, 18, "Cumilla Sadar", "Cumilla Sadar", "cumilla-sadar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL),
            (566, 6, "Dasar", "Dasar", "dasar", NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL)');

    }
}
